export enum Estado {
  CREADO                         = "CREADO",
  EN_TRANSITO_LAB_A_LOGISTICA    = "EN_TRANSITO_LAB_A_LOGISTICA",
  ALMACENADO_LOGISTICA           = "ALMACENADO_LOGISTICA",
  EN_TRANSITO_LOGISTICA_A_SALUD  = "EN_TRANSITO_LOGISTICA_A_SALUD",
  RECIBIDO_SALUD                 = "RECIBIDO_SALUD",
  DESPACHADO_PACIENTE          = "DESPACHADO_PACIENTE"
}